publisher_port_joint_trajectory_controller:
  ros__parameters:

    controller_name: "port_joint_trajectory_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1: [-1.57, 3.14, 0.785, 0.785, 0.785, 0.785]
    pos2: [-1.57, 3.925, 0.0, -1.57, 0.0, -0.785]
    pos3: [-1.57, 3.14, 0.0, 0.0, -0.785, 0.0]
    pos4: [-1.57, 3.14, 0.0, -1.57, 0.0, 0.0]

    joints:
      - port_shoulder_pan_joint
      - port_shoulder_lift_joint
      - port_elbow_joint
      - port_wrist_1_joint
      - port_wrist_2_joint
      - port_wrist_3_joint

    check_starting_point: false
    starting_point_limits:
      port_shoulder_pan_joint: [-0.1,0.1]
      port_shoulder_lift_joint: [-1.6,-1.5]
      port_elbow_joint: [-0.1,0.1]
      port_wrist_1_joint: [-1.6,-1.5]
      port_wrist_2_joint: [-0.1,0.1]
      port_wrist_3_joint: [-0.1,0.1]


publisher_starboard_joint_trajectory_controller:
  ros__parameters:

    controller_name: "starboard_joint_trajectory_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1: [1.57, -1.57, 0.785, 0.785, 0.785, 0.785]
    pos2: [1.57, -0.785, 0.0, -0.785, 0.0, 0.785]
    pos3: [1.57, -1.57, 0.0, 0.0, -0.785, 0.0]
    pos4: [1.57, 0.0, 0.0, -1.57, 0.0, 0.0]

    joints:
      - starboard_shoulder_pan_joint
      - starboard_shoulder_lift_joint
      - starboard_elbow_joint
      - starboard_wrist_1_joint
      - starboard_wrist_2_joint
      - starboard_wrist_3_joint

    check_starting_point: false
    starting_point_limits:
      starboard_shoulder_pan_joint: [-0.1,0.1]
      starboard_shoulder_lift_joint: [-1.6,-1.5]
      starboard_elbow_joint: [-0.1,0.1]
      starboard_wrist_1_joint: [-1.6,-1.5]
      starboard_wrist_2_joint: [-0.1,0.1]
      starboard_wrist_3_joint: [-0.1,0.1]
