name: Humble bloom-release

on:
  push:
    paths:
       - package.xml
       - '*/package.xml'
    branches: humble
  workflow_dispatch:

jobs:
  bloom-release:
    runs-on: ubuntu-22.04
    container:
      image: osrf/ros:humble-desktop
    env:
      ROS_DISTRO: humble
      PRERELEASE: true
      BASEDIR: ${{ github.workspace }}/.work

    steps:
      - name: checkout
        uses: actions/checkout@v2

      # - uses: ros-tooling/setup-ros@v0.2
      #   with:
      #     required-ros-distributions: galactic

      # BASIC CODE QUALITY
      # - run: |
      #     sudo apt-get update
      #     sudo apt-get install -y clang-format-12

      # - uses: actions/setup-python@v3
      #   with:
      #     python-version: 3.9

      # - name: code quality check
      #   uses: pre-commit/action@v3.0.0

      # BLOOM PRERELEASE CHECK
      # - name: industrial_ci prerelease check
      #   uses: ros-industrial/industrial_ci@master
      - shell: bash
        run: |
          apt-get update
          apt-get install -y python3-colcon-* python3-colcon-coveragepy-result
          source /opt/ros/humble/setup.bash
          rosdep update
          rosdep install --from-paths . --ignore-src -r -y --skip-keys warehouse_ros_mongo
          colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-up-to smacc2 smacc2_msgs

      # - uses: ros-tooling/action-ros-ci@v0.2
      #   with:
      #     package-name: smacc2 smacc2_msgs
      #     target-ros2-distro: humble
      #     vcs-repo-file-url: SMACC2.humble.repos

      # BLOOM RELEASE
      - name: bloom release
        uses: at-wat/bloom-release-action@v0
        with:
          ros_distro: ${{ env.ROS_DISTRO }}
          github_token_bloom: ${{ secrets.GITTOKEN_BLOOM }}
          github_user: pabloinigoblasco
          git_user: pabloinigoblasco
          git_email: pablo@ibrobotics.com
          release_repository_push_url: https://github.com/robosoft-ai/SMACC2-release
          tag_and_release: true
          # open_pr: true
